# User API

In [1]:
%config InlineBackend.print_figure_kwargs = {'bbox_inches': 'tight', 'dpi': 110}
%load_ext autoreload
%autoreload 2
import logging, warnings
logging.getLogger("pymc").setLevel(logging.FATAL)
warnings.filterwarnings("ignore")

## PyMC

The [Example](example.html) page introduces how to use *muse-inference* for a problem defined with PyMC. Here we consider a more complex problem to highlight additional features. In particular:

* We can estimate any number of parameters with any shapes. Here we have a 2-dimensional array $\mu$ and a scalar $\theta$. Note that by default, *muse-inference* considers any variables which do not depend on others as "parameters" (i.e. the "leaves" of the probabilistic graph). However, the algorithm is not limited to such parameters, and any choice can be selected by providing a list of `params` to the `PyMCMuseProblem` constructor.

* We can work with distributions with limited domain support. For example, below we use the $\rm Beta$ distribution with support on $(0,1)$ and the $\rm LogNormal$ distribution with support on $(0,\infty)$. All necessary transformations are handled internally.

* The data and latent space can include any number of variables, with any shapes. Below we demonstrate an $x$ and $z$ which are 2-dimensional arrays. 

First, load the relevant packages:

In [2]:
%pylab inline
import pymc as pm
from muse_inference.pymc import PyMCMuseProblem

Populating the interactive namespace from numpy and matplotlib


Then define the problem,

In [3]:
def gen_funnel(x=None, σ=None, μ=None, rng=None):
    with pm.Model(rng_seeder=rng) as model:
        μ = pm.Beta("μ", 2, 5, size=2) if μ is None else μ
        σ = pm.Normal("σ", 0, 3) if σ is None else σ
        z = pm.LogNormal("z", μ, np.exp(σ/2), size=(100, 2))
        x = pm.Normal("x", z, 1, observed=x)
    return model

generate the model and some data, given some chosen true values of parameters,

In [4]:
θ_true = dict(μ=[0.3, 0.7], σ=1)
x_obs = pm.sample_prior_predictive(1, gen_funnel(rng=RandomState(0), **θ_true)).prior.x[0,0]
model = gen_funnel(x=x_obs)
prob = PyMCMuseProblem(model)

and finally, run MUSE:

In [5]:
θ_start = dict(μ=[0.5, 0.5], σ=0)
result = prob.solve(θ_start=θ_start, progress=True)

MUSE:   0%|          | 0/5050 [00:00<?, ?it/s]

MUSE:   0%|          | 9/5050 [00:00<00:58, 85.72it/s]

MUSE:   0%|          | 18/5050 [00:00<00:59, 85.26it/s]

MUSE:   1%|          | 28/5050 [00:00<00:56, 89.25it/s]

MUSE:   1%|          | 37/5050 [00:00<01:00, 83.01it/s]

MUSE:   1%|          | 46/5050 [00:00<00:58, 85.02it/s]

MUSE:   1%|          | 55/5050 [00:00<00:57, 86.24it/s]

MUSE:   1%|▏         | 64/5050 [00:00<00:58, 84.80it/s]

MUSE:   1%|▏         | 74/5050 [00:00<00:56, 87.72it/s]

MUSE:   2%|▏         | 84/5050 [00:00<00:54, 90.67it/s]

MUSE:   2%|▏         | 94/5050 [00:01<00:54, 90.67it/s]

MUSE:   2%|▏         | 104/5050 [00:01<01:24, 58.51it/s]

MUSE:   2%|▏         | 112/5050 [00:01<01:21, 60.89it/s]

MUSE:   2%|▏         | 120/5050 [00:01<01:17, 63.26it/s]

MUSE:   3%|▎         | 128/5050 [00:01<01:16, 64.29it/s]

MUSE:   3%|▎         | 136/5050 [00:01<01:20, 60.80it/s]

MUSE:   3%|▎         | 143/5050 [00:01<01:21, 59.99it/s]

MUSE:   3%|▎         | 151/5050 [00:02<01:18, 62.49it/s]

MUSE:   3%|▎         | 159/5050 [00:02<01:15, 65.00it/s]

MUSE:   3%|▎         | 166/5050 [00:02<01:18, 62.48it/s]

MUSE:   3%|▎         | 173/5050 [00:02<01:18, 61.91it/s]

MUSE:   4%|▎         | 182/5050 [00:02<01:13, 66.14it/s]

MUSE:   4%|▎         | 189/5050 [00:02<01:13, 66.42it/s]

MUSE:   4%|▍         | 196/5050 [00:02<01:20, 60.15it/s]

MUSE:   4%|▍         | 203/5050 [00:03<01:55, 41.98it/s]

MUSE:   4%|▍         | 212/5050 [00:03<01:34, 51.24it/s]

MUSE:   4%|▍         | 222/5050 [00:03<01:20, 60.29it/s]

MUSE:   5%|▍         | 233/5050 [00:03<01:07, 71.84it/s]

MUSE:   5%|▍         | 242/5050 [00:03<01:05, 73.01it/s]

MUSE:   5%|▍         | 251/5050 [00:03<01:03, 75.10it/s]

MUSE:   5%|▌         | 261/5050 [00:03<00:58, 81.48it/s]

MUSE:   5%|▌         | 271/5050 [00:03<00:56, 84.72it/s]

MUSE:   6%|▌         | 280/5050 [00:03<00:55, 85.90it/s]

MUSE:   6%|▌         | 289/5050 [00:04<00:56, 84.70it/s]

MUSE:   6%|▌         | 299/5050 [00:04<00:54, 86.64it/s]

MUSE:   6%|▌         | 308/5050 [00:04<01:21, 58.12it/s]

MUSE:   6%|▋         | 326/5050 [00:04<00:56, 83.38it/s]

MUSE:   7%|▋         | 341/5050 [00:04<00:47, 98.12it/s]

MUSE:   7%|▋         | 360/5050 [00:04<00:39, 118.71it/s]

MUSE:   7%|▋         | 374/5050 [00:04<00:41, 113.84it/s]

MUSE:   8%|▊         | 391/5050 [00:05<00:36, 127.48it/s]

MUSE:   8%|▊         | 405/5050 [00:05<00:52, 88.43it/s] 

MUSE:   8%|▊         | 424/5050 [00:05<00:43, 107.47it/s]

MUSE:   9%|▉         | 443/5050 [00:05<00:36, 125.20it/s]

MUSE:   9%|▉         | 458/5050 [00:05<00:35, 128.14it/s]

MUSE:   9%|▉         | 477/5050 [00:05<00:31, 143.62it/s]

MUSE:  10%|▉         | 498/5050 [00:05<00:28, 158.88it/s]

MUSE:  10%|█         | 516/5050 [00:06<00:40, 112.39it/s]

MUSE:  11%|█         | 536/5050 [00:06<00:34, 130.39it/s]

MUSE:  11%|█         | 562/5050 [00:06<00:28, 156.45it/s]

MUSE:  12%|█▏        | 585/5050 [00:06<00:25, 171.93it/s]

MUSE:  12%|█▏        | 607/5050 [00:06<00:34, 127.62it/s]

MUSE:  12%|█▏        | 629/5050 [00:06<00:30, 144.20it/s]

MUSE:  13%|█▎        | 653/5050 [00:06<00:26, 163.47it/s]

MUSE:  13%|█▎        | 681/5050 [00:07<00:23, 189.94it/s]

MUSE:  14%|█▍        | 708/5050 [00:07<00:29, 145.76it/s]

MUSE:  15%|█▍        | 741/5050 [00:07<00:23, 181.91it/s]

MUSE:  15%|█▌        | 770/5050 [00:07<00:21, 203.72it/s]

MUSE:  16%|█▌        | 800/5050 [00:07<00:19, 222.65it/s]

MUSE:  16%|█▋        | 826/5050 [00:07<00:24, 170.66it/s]

MUSE:  18%|█▊        | 904/5050 [00:07<00:13, 297.50it/s]

MUSE:  19%|█▊        | 942/5050 [00:08<00:17, 239.85it/s]

MUSE:  20%|██        | 1011/5050 [00:08<00:16, 243.87it/s]

MUSE:  22%|██▏       | 1100/5050 [00:08<00:11, 355.87it/s]

MUSE:  23%|██▎       | 1148/5050 [00:08<00:13, 293.53it/s]

MUSE: 100%|██████████| 5050/5050 [00:09<00:00, 5578.41it/s]

MUSE: 100%|██████████| 5050/5050 [00:09<00:00, 556.60it/s] 

get_H:   0%|          | 0/70 [00:00<?, ?it/s]

get_H:   6%|▌         | 4/70 [00:00<00:01, 38.98it/s]

get_H:  11%|█▏        | 8/70 [00:00<00:01, 36.20it/s]

get_H:  19%|█▊        | 13/70 [00:00<00:01, 39.57it/s]

get_H:  24%|██▍       | 17/70 [00:00<00:01, 39.16it/s]

get_H:  30%|███       | 21/70 [00:00<00:01, 39.26it/s]

get_H:  37%|███▋      | 26/70 [00:00<00:01, 42.15it/s]

get_H:  44%|████▍     | 31/70 [00:00<00:00, 44.35it/s]

get_H:  51%|█████▏    | 36/70 [00:00<00:00, 44.61it/s]

get_H:  60%|██████    | 42/70 [00:00<00:00, 46.15it/s]

get_H:  67%|██████▋   | 47/70 [00:01<00:00, 45.96it/s]

get_H:  74%|███████▍  | 52/70 [00:01<00:00, 46.06it/s]

get_H:  83%|████████▎ | 58/70 [00:01<00:00, 49.51it/s]

get_H:  90%|█████████ | 63/70 [00:01<00:00, 46.95it/s]

get_H:  97%|█████████▋| 68/70 [00:01<00:00, 46.43it/s]

get_H: 100%|██████████| 70/70 [00:01<00:00, 44.36it/s]

When there are multiple parameters, the starting guess should be specified as as a dictionary, as above.

The parameter estimate is returned as a dictionary,

In [6]:
result.θ

{'μ': array([0.33948043, 0.52322182]), 'σ': array(0.79285756)}

 and the covariance as matrix, with parameters concatenated in the order they appear in the model (or in the order specified in `params`, if that was used):

In [7]:
result.Σ

array([[ 0.02566017,  0.00588293, -0.00267772],
       [ 0.00588293,  0.01675884, -0.00143907],
       [-0.00267772, -0.00143907,  0.00938469]])

The `result.ravel` and `result.unravel` functions can be used to convert between dictionary and vector representations of the parameters. For example, to compute the standard deviation for each parameter (the square root of the diagonal of the covariance):

In [8]:
result.unravel(np.sqrt(np.diag(result.Σ)))

{'μ': array([0.16018792, 0.12945595]), 'σ': array(0.09687461)}

or to convert the mean parameters to a vector:

In [9]:
result.ravel(result.θ)

array([0.33948043, 0.52322182, 0.79285756])

## Jax

We can also use [Jax](https://jax.readthedocs.io/) to define the problem. In this case we will write out function to generate forward samples and to compute the posterior, and Jax will provide necessary gradients for free. To use Jax, load the necessary packages:

In [10]:
from functools import partial
import jax
import jax.numpy as jnp
from muse_inference.jax import JittableJaxMuseProblem, JaxMuseProblem

Let's implement the noisy funnel problem from the [Example](example.html) page. To do so, extend either `JaxMuseProblem`, or, if your code is able to be JIT compiled by Jax, extend `JittableJaxMuseProblem` and decorate the functions with `jax.jit`:

In [11]:
class JaxFunnelMuseProblem(JittableJaxMuseProblem):

    def __init__(self, N):
        super().__init__()
        self.N = N

    @partial(jax.jit, static_argnums=0)
    def sample_x_z(self, key, θ):
        keys = jax.random.split(key, 2)
        z = jax.random.normal(keys[0], (self.N,)) * jnp.exp(θ/2)
        x = z + jax.random.normal(keys[1], (self.N,))
        return (x, z)

    @partial(jax.jit, static_argnums=0)
    def logLike(self, x, z, θ):
        return -(jnp.sum((x - z)**2) + jnp.sum(z**2) / jnp.exp(θ) + 512*θ) / 2

    @partial(jax.jit, static_argnums=0)
    def logPrior(self, θ):
        return -θ**2 / (2*3**2)

Now generate some simulated data, which we set into `prob.x`. Note also the use of `PRNGKey` (rather than `RandomState` for PyMC/Numpy) for random number generation. 

In [12]:
prob = JaxFunnelMuseProblem(10000)
key = jax.random.PRNGKey(0)
(x, z) = prob.sample_x_z(key, 0)
prob.x = x

And finally, run MUSE:

In [13]:
prob.solve(θ_start=0., rng=jax.random.PRNGKey(1)) # warmup

In [14]:
result = prob.solve(θ_start=0., rng=jax.random.PRNGKey(1), progress=True)

MUSE:   0%|          | 0/5050 [00:00<?, ?it/s]

MUSE:   2%|▏         | 102/5050 [00:00<00:05, 881.90it/s]

MUSE:   4%|▍         | 203/5050 [00:00<00:07, 674.48it/s]

MUSE:   6%|▌         | 304/5050 [00:00<00:07, 658.41it/s]

MUSE:   8%|▊         | 384/5050 [00:00<00:06, 698.97it/s]

MUSE: 100%|██████████| 5050/5050 [00:00<00:00, 14307.80it/s]

MUSE: 100%|██████████| 5050/5050 [00:00<00:00, 7746.18it/s] 

get_H:   0%|          | 0/30 [00:00<?, ?it/s]

get_H: 100%|██████████| 30/30 [00:00<00:00, 407.97it/s]

Note that the solution here is obtained around 10X faster that the PyMC version of this in the [Example](example.html) page (the cloud machines which build these docs don't always achieve the 10X, but you see this if you run these examples locally). The Jax interface has much lower overhead, which will be noticeable for very fast posteriors like the one above. 

One convenient aspect of using Jax is that the parameters, `θ`, and latent space, `z`, can be any [pytree](https://jax.readthedocs.io/en/latest/pytrees.html), ie tuples, dictionaries, nested combinations of them, etc... (there is no requirement on the data format of the `x` variable). To demonstrate, consider a problem which is just two copies of the noisy funnel problem:

In [15]:
class JaxPyTreeFunnelMuseProblem(JittableJaxMuseProblem):

    def __init__(self, N):
        super().__init__()
        self.N = N

    @partial(jax.jit, static_argnums=0)
    def sample_x_z(self, key, θ):
        (θ1, θ2) = (θ["θ1"], θ["θ2"])
        keys = jax.random.split(key, 4)
        z1 = jax.random.normal(keys[0], (self.N,)) * jnp.exp(θ1/2)
        z2 = jax.random.normal(keys[1], (self.N,)) * jnp.exp(θ2/2)        
        x1 = z1 + jax.random.normal(keys[2], (self.N,))
        x2 = z2 + jax.random.normal(keys[3], (self.N,))        
        return ({"x1":x1, "x2":x2}, {"z1":z1, "z2":z2})

    @partial(jax.jit, static_argnums=0)
    def logLike(self, x, z, θ):
        return (
            -(jnp.sum((x["x1"] - z["z1"])**2) + jnp.sum(z["z1"]**2) / jnp.exp(θ["θ1"]) + 512*θ["θ1"]) / 2
            -(jnp.sum((x["x2"] - z["z2"])**2) + jnp.sum(z["z2"]**2) / jnp.exp(θ["θ2"]) + 512*θ["θ2"]) / 2
        )

    @partial(jax.jit, static_argnums=0)
    def logPrior(self, θ):
        return - θ["θ1"]**2 / (2*3**2) - θ["θ2"]**2 / (2*3**2)

Here, `x`, `θ`, and `z` are all dictionaries. We generate the problem as usual, passing in parameters as dictionaries,

In [16]:
θ_true = dict(θ1=-1., θ2=2.)
θ_start = dict(θ1=0., θ2=0.)

In [17]:
prob = JaxPyTreeFunnelMuseProblem(10000)
key = jax.random.PRNGKey(0)
(x, z) = prob.sample_x_z(key, θ_true)
prob.x = x

and run MUSE:

In [18]:
prob.solve(θ_start=θ_start, rng=jax.random.PRNGKey(0)) # warmup

In [19]:
result = prob.solve(θ_start=θ_start, rng=jax.random.PRNGKey(0), progress=True)

MUSE:   0%|          | 0/5050 [00:00<?, ?it/s]

MUSE:   2%|▏         | 102/5050 [00:00<00:10, 457.60it/s]

MUSE:   3%|▎         | 148/5050 [00:00<00:11, 443.19it/s]

MUSE:   4%|▍         | 192/5050 [00:00<00:11, 436.13it/s]

MUSE:   5%|▍         | 236/5050 [00:00<00:17, 281.97it/s]

MUSE:   5%|▌         | 269/5050 [00:00<00:16, 283.56it/s]

MUSE:   6%|▌         | 301/5050 [00:00<00:16, 288.17it/s]

MUSE:   7%|▋         | 332/5050 [00:01<00:22, 213.68it/s]

MUSE:   7%|▋         | 358/5050 [00:01<00:21, 222.72it/s]

MUSE:   8%|▊         | 387/5050 [00:01<00:19, 236.73it/s]

MUSE:   8%|▊         | 414/5050 [00:01<00:24, 186.28it/s]

MUSE:   9%|▉         | 447/5050 [00:01<00:21, 215.53it/s]

MUSE:   9%|▉         | 477/5050 [00:01<00:19, 234.74it/s]

MUSE:  10%|█         | 506/5050 [00:02<00:24, 186.43it/s]

MUSE:  11%|█         | 541/5050 [00:02<00:20, 220.67it/s]

MUSE:  11%|█▏        | 577/5050 [00:02<00:17, 251.56it/s]

MUSE:  12%|█▏        | 607/5050 [00:02<00:22, 200.32it/s]

MUSE:  13%|█▎        | 640/5050 [00:02<00:19, 226.24it/s]

MUSE:  13%|█▎        | 671/5050 [00:02<00:17, 244.66it/s]

MUSE:  14%|█▍        | 702/5050 [00:02<00:16, 260.35it/s]

MUSE:  14%|█▍        | 731/5050 [00:03<00:21, 198.76it/s]

MUSE:  15%|█▌        | 762/5050 [00:03<00:19, 222.38it/s]

MUSE:  16%|█▌        | 793/5050 [00:03<00:17, 242.74it/s]

MUSE:  16%|█▋        | 821/5050 [00:03<00:22, 189.81it/s]

MUSE:  17%|█▋        | 853/5050 [00:03<00:19, 217.04it/s]

MUSE:  17%|█▋        | 882/5050 [00:03<00:17, 232.37it/s]

MUSE:  18%|█▊        | 910/5050 [00:03<00:22, 183.23it/s]

MUSE:  19%|█▊        | 941/5050 [00:03<00:19, 209.46it/s]

MUSE:  19%|█▉        | 974/5050 [00:04<00:17, 236.37it/s]

MUSE:  20%|█▉        | 1003/5050 [00:04<00:16, 248.26it/s]

MUSE:  20%|██        | 1031/5050 [00:04<00:19, 204.52it/s]

MUSE:  21%|██▏       | 1080/5050 [00:04<00:14, 269.39it/s]

MUSE:  22%|██▏       | 1112/5050 [00:04<00:17, 228.19it/s]

MUSE:  23%|██▎       | 1162/5050 [00:04<00:13, 288.04it/s]

MUSE:  24%|██▍       | 1212/5050 [00:04<00:11, 338.04it/s]

MUSE:  25%|██▍       | 1251/5050 [00:05<00:13, 282.13it/s]

MUSE:  26%|██▌       | 1306/5050 [00:05<00:10, 341.18it/s]

MUSE:  27%|██▋       | 1346/5050 [00:05<00:13, 282.85it/s]

MUSE:  28%|██▊       | 1397/5050 [00:05<00:11, 329.58it/s]

MUSE:  28%|██▊       | 1436/5050 [00:05<00:13, 268.58it/s]

MUSE:  29%|██▉       | 1479/5050 [00:05<00:11, 301.46it/s]

MUSE:  30%|███       | 1516/5050 [00:06<00:14, 246.85it/s]

MUSE:  31%|███       | 1562/5050 [00:06<00:12, 289.96it/s]

MUSE:  32%|███▏      | 1603/5050 [00:06<00:10, 315.66it/s]

MUSE:  32%|███▏      | 1640/5050 [00:06<00:13, 256.17it/s]

MUSE:  33%|███▎      | 1686/5050 [00:06<00:11, 298.28it/s]

MUSE:  34%|███▍      | 1721/5050 [00:06<00:13, 243.88it/s]

MUSE:  35%|███▌      | 1774/5050 [00:06<00:10, 301.54it/s]

MUSE:  36%|███▌      | 1819/5050 [00:07<00:12, 264.26it/s]

MUSE:  37%|███▋      | 1856/5050 [00:07<00:11, 285.76it/s]

MUSE:  38%|███▊      | 1894/5050 [00:07<00:10, 305.71it/s]

MUSE: 100%|██████████| 5050/5050 [00:07<00:00, 6187.61it/s]

MUSE: 100%|██████████| 5050/5050 [00:07<00:00, 672.81it/s] 

get_H:   0%|          | 0/50 [00:00<?, ?it/s]

get_H:  42%|████▏     | 21/50 [00:00<00:00, 200.34it/s]

get_H:  84%|████████▍ | 42/50 [00:00<00:00, 194.77it/s]

get_H: 100%|██████████| 50/50 [00:00<00:00, 197.69it/s]

The result is returned as a pytree:

In [20]:
result.θ

{'θ1': DeviceArray(-1.0024003, dtype=float32),
 'θ2': DeviceArray(2.0271273, dtype=float32)}

and the covariance as a matrix:

In [21]:
result.Σ

array([[ 3.3699032e-03, -1.7559714e-05],
       [-1.7559714e-05,  2.4587807e-04]], dtype=float32)

The `result.ravel` and `result.unravel` functions can be used to convert between pytree and vector representations of the parameters. For example, to compute the standard deviation for each parameter (the square root of the diagonal of the covariance):

In [22]:
result.unravel(np.sqrt(np.diag(result.Σ)))

{'θ1': DeviceArray(0.05805087, dtype=float32),
 'θ2': DeviceArray(0.0156805, dtype=float32)}

or to convert the mean parameters to a vector:

In [23]:
result.ravel(result.θ)

DeviceArray([-1.0024003,  2.0271273], dtype=float32)